/******************************************************************************************************************
 * ProviderService.java
 *
 *          Provides the CRUD operations and certain find queries for getting the provider data.
 *
 * @author Matthew Kiyono
 * @since 12/6/2025
 * @version 1.0
 ******************************************************************************************************************/

package com.appointmentProject.backend.service;

import com.appointmentProject.backend.exception.RecordNotFoundException;
import com.appointmentProject.backend.model.Provider;
import com.appointmentProject.backend.repository.ProviderRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;

@Service
public class ProviderService {

    @Autowired
    private ProviderRepository providerRepo;

    // CREATE
    public Provider addProvider(Provider provider) {
        // ID will be auto-generated by MySQL (IDENTITY)
        return providerRepo.save(provider);
    }

    // READ ALL
    public List<Provider> getAllProviders() {
        return providerRepo.findAll();
    }

    // READ ONE
    public Provider getById(int id) {
        return providerRepo.findById(id)
                .orElseThrow(() ->
                        new RecordNotFoundException("Provider with id " + id + " not found.")
                );
    }

    // UPDATE
    public Provider updateProvider(int id, Provider updated) {
        Provider existing = getById(id); // throws if not found

        // Update fields (Person fields + provider-specific)
        existing.setFirstName(updated.getFirstName());
        existing.setLastName(updated.getLastName());
        existing.setPhone(updated.getPhone());
        existing.setEmail(updated.getEmail());
        existing.setSpecialty(updated.getSpecialty());
        existing.setAddress(updated.getAddress());

        return providerRepo.save(existing);
    }

    // DELETE
    public void deleteProvider(int id) {
        if (!providerRepo.existsById(id)) {
            throw new RecordNotFoundException("Cannot delete. Provider with id " + id + " not found.");
        }
        providerRepo.deleteById(id);
    }
}
